env:
  CIRRUS_CLONE_DEPTH: 1

freebsd_1st_task:
  freebsd_instance:
    image_family: freebsd-12-1
    cpu: 4
    memory: 4G
  install_script: ASSUME_ALWAYS_YES=yes pkg bootstrap -f ; pkg install -y
    bash curl cyrus-sasl git glib gmake gnutls gsed
    nettle perl5 pixman pkgconf png usbredir
  script:
    - mkdir build
    - cd build
    - ../configure --disable-user --target-list-exclude='alpha-softmmu
        ppc64-softmmu ppc-softmmu riscv32-softmmu riscv64-softmmu s390x-softmmu
        sparc64-softmmu sparc-softmmu x86_64-softmmu i386-softmmu'
        --enable-werror || { cat config.log; exit 1; }
    - gmake -j$(sysctl -n hw.ncpu)
    - gmake -j$(sysctl -n hw.ncpu) check

freebsd_2nd_task:
  freebsd_instance:
    image_family: freebsd-12-1
    cpu: 4
    memory: 4G
  install_script: ASSUME_ALWAYS_YES=yes pkg bootstrap -f ; pkg install -y
    bash curl cyrus-sasl git glib gmake gnutls gtk3 gsed libepoxy mesa-libs
    nettle perl5 pixman pkgconf png SDL2 usbredir
  script:
    - ./configure --enable-werror --target-list='alpha-softmmu ppc64-softmmu
        ppc-softmmu riscv32-softmmu riscv64-softmmu s390x-softmmu
        sparc64-softmmu sparc-softmmu x86_64-softmmu i386-softmmu
        sparc-bsd-user sparc64-bsd-user x86_64-bsd-user i386-bsd-user'
        || { cat config.log; exit 1; }
    - gmake -j$(sysctl -n hw.ncpu)
    - gmake -j$(sysctl -n hw.ncpu) check

macos_task:
  osx_instance:
    image: catalina-base
  install_script:
    - brew install pkg-config python gnu-sed glib pixman make sdl2 bash
  script:
    - mkdir build
    - cd build
    - ../configure --python=/usr/local/bin/python3 --enable-werror
                   --extra-cflags='-Wno-error=deprecated-declarations'
                   || { cat config.log; exit 1; }
    - gmake -j$(sysctl -n hw.ncpu)
    - gmake check

macos_xcode_task:
  osx_instance:
    # this is an alias for the latest Xcode
    image: catalina-xcode
  install_script:
    - brew install pkg-config gnu-sed glib pixman make sdl2 bash
  script:
    - mkdir build
    - cd build
    - ../configure --extra-cflags='-Wno-error=deprecated-declarations'
                   --enable-werror --cc=clang || { cat config.log; exit 1; }
    - gmake -j$(sysctl -n hw.ncpu)
    - gmake check

windows_msys2_task:
  windows_container:
    image: cirrusci/windowsservercore:cmake
    os_version: 2019
    cpu: 8
    memory: 8G
  env:
    MSYS: winsymlinks:nativestrict
    MSYSTEM: MINGW64
    CHERE_INVOKING: 1
  printenv_script:
    - C:\tools\msys64\usr\bin\bash.exe -lc 'printenv'
  install_script:
    - C:\tools\msys64\usr\bin\bash.exe -lc "cd /c/tools && curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
    - C:\tools\msys64\usr\bin\bash.exe -lc "cd /c/tools && curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig"
    - C:\tools\msys64\usr\bin\bash.exe -lc "cd /c/tools && pacman -U --noconfirm msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz"
    - C:\tools\msys64\usr\bin\bash.exe -lc "pacman -Sy --noconfirm"
    - C:\tools\msys64\usr\bin\bash.exe -lc "pacman --needed --noconfirm -S bash pacman pacman-mirrors msys2-runtime"
    - taskkill /F /IM gpg-agent.exe
    - C:\tools\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -Su"
    - C:\tools\msys64\usr\bin\bash.exe -lc "sh scripts/ci/windows/msys2-install.sh"
  script:
    - C:\tools\msys64\usr\bin\bash.exe -lc "sh scripts/ci/windows/msys2-build.sh"
